title: MikiCutie Bot Docs
description: A Website with all my documentation regaridng MikiCutie Bot.
theme: just-the-docs

url: https://l0xdev.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
